## Простой Метод Гаусса

In [19]:
import numpy as np

def simple_gauss_method(A, b):
    """
    Простой метод Гаусса (без выбора опорного элемента):
    прямой ход + обратная подстановка.
    """
    A = A.astype(float)
    b = b.astype(float)
    n = len(b)

    # Прямой ход
    for i in range(n):
        if abs(A[i, i]) < 1e-12:
            raise ValueError("Нулевой или почти нулевой диагональный элемент.")
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
            b[j] -= factor * b[i]

    # Обратный ход
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    return x

#### Пример использования:

In [26]:
A = np.array([
    [2, 3],
    [4, 9]
])
b = np.array([8, 20])

solution = simple_gauss_method(A, b)
print("Решение:\n", solution)

Решение:
 [2.         1.33333333]


## Метод Жордана-Гаусса

In [27]:
def gauss_jordan(A, b):
    
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float).reshape(-1, 1)
    n = len(b)

    # Расширенная матрица [A | b]
    Ab = np.hstack((A, b))

    # Прямой и обратный ход (Жордана)
    for i in range(n):
        pivot = Ab[i, i]
        if abs(pivot) < 1e-12:
            raise ValueError("Нулевой или почти нулевой ведущий элемент.")
        Ab[i] = Ab[i] / pivot  # делаем ведущий элемент = 1

        for k in range(n):
            if k != i:
                factor = Ab[k, i]
                Ab[k] -= factor * Ab[i]

    # Ответ — последний столбец
    return Ab[:, -1]

#### Пример использования:

In [28]:
solution = gauss_jordan(A, b)

print("Решение:\n", solution)

Решение:
 [2.         1.33333333]


## Метод Гаусса с методом исключения

In [23]:
def gauss_elimination_only(A, b):
    """
    Метод Гаусса с методом исключения (только прямой ход).
    Возвращает верхнетреугольную матрицу и изменённый вектор b.
    """
    A = A.astype(float)
    b = b.astype(float)
    n = len(b)

    # Прямой ход
    for i in range(n):
        if abs(A[i, i]) < 1e-12:
            raise ValueError("Нулевой или почти нулевой диагональный элемент.")
        for j in range(i + 1, n):
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]
            b[j] -= factor * b[i]

    return A, b

In [25]:
solution = gauss_elimination_only(A, b)

print("Решение:\n", solution)

Решение:
 (array([[2., 3.],
       [0., 3.]]), array([8., 4.]))


## Метод LU-разложения

In [30]:
def lu_decomposition(A):
    """
    Выполняет LU-разложение матрицы A без выбора главного элемента.
    Возвращает L и U такие, что A = L @ U
    """
    A = np.array(A, dtype=float)
    n = A.shape[0]
    
    L = np.eye(n)
    U = np.zeros_like(A)

    for i in range(n):
        for j in range(i, n):  # элементы верхнего треугольника
            U[i, j] = A[i, j] - np.dot(L[i, :i], U[:i, j])
        for j in range(i + 1, n):  # элементы нижнего треугольника
            if abs(U[i, i]) < 1e-12:
                raise ValueError("Нулевой элемент на диагонали — разложение невозможно без перестановки.")
            L[j, i] = (A[j, i] - np.dot(L[j, :i], U[:i, i])) / U[i, i]
    
    return L, U

def forward_substitution(L, b):
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    return y

def backward_substitution(U, y):
    n = len(y)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]
    return x

In [31]:
L, U = lu_decomposition(A)
print("L =\n", L)
print("U =\n", U)

y = forward_substitution(L, b)
x = backward_substitution(U, y)

print("Решение x:", x)

L =
 [[1. 0.]
 [2. 1.]]
U =
 [[2. 3.]
 [0. 3.]]
Решение x: [2.         1.33333333]
