In [1]:
import numpy as np


def jacobi_eigen(A, eps=1e-10, max_iter=100):
    n = A.shape[0]

    # Проверяем на симметричность:
    if not np.allclose(A, A.T):
        print(ValueError("Матрица должна быть симметричной"))
        return -1

    # Матрица собственных векторов:
    V = np.eye(n)

    for _ in range(max_iter):

        # Максимальный по модулю недиагональный элемент:
        max_val = 0
        p, q = 0, 0
        for i in range(n):
            for j in range(i + 1, n):
                if abs(A[i, j]) > max_val:
                    max_val = abs(A[i, j])
                    p, q = i, j

        # Проверяем на достижение точности
        if max_val < eps:
            break

        # Вычисляем угол поворота
        if A[p, p] == A[q, q]:
            phi = np.pi / 4
        else:
            phi = 0.5 * np.arctan(2 * A[p, q] / (A[p, p] - A[q, q]))

        # Формируем матрицу вращения
        H = np.eye(n)
        c = np.cos(phi)
        s = np.sin(phi)
        H[p, p] = c
        H[q, q] = c
        H[p, q] = -s
        H[q, p] = s

        # Матричное перемножение
        A = H.T @ A @ H

        V = V @ H

    # Собственные значения - диагональные элементы
    eigenvalues = np.diag(A)
    # Собственные векторы - столбцы матрицы V
    eigenvectors = V

    return eigenvalues, eigenvectors


In [2]:
# Проверяем работу
A = np.array([[5, 1],
              [1, 4]])

print("Исходная матрица:")
print(A)

eigenvalues, eigenvectors = jacobi_eigen(A)

print("\nСобственные значения: ")
print(eigenvalues)

print("\nСобственные векторы (в столбцах): ")
print(eigenvectors)

Исходная матрица:
[[5 1]
 [1 4]]

Собственные значения: 
[5.61803399 3.38196601]

Собственные векторы (в столбцах): 
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]


In [3]:
# Матрица 3x3
A = np.array([[5, 1, 2],
              [1, 4, 1],
              [2, 1, 3]])

print("Исходная матрица:")
print(A)

eigenvalues, eigenvectors = jacobi_eigen(A)

print("\nСобственные значения: ")
print(eigenvalues)

print("\nСобственные векторы (в столбцах): ")
print(eigenvectors)

Исходная матрица:
[[5 1 2]
 [1 4 1]
 [2 1 3]]

Собственные значения: 
[6.89510652 3.39729507 1.70759841]

Собственные векторы (в столбцах): 
[[ 0.75257583 -0.45794385 -0.47319874]
 [ 0.43170413  0.88573564 -0.17059871]
 [ 0.49725362 -0.07589338  0.86427949]]
