In [1]:
import numpy as np

In [2]:
# Попытка привести матрицу к диагонально-доминантному виду
def make_diagonally_dominant(A, b):
    n = len(A)
    new_A = np.zeros_like(A)
    new_b = np.zeros_like(b)
    remaining_rows = set(range(n))

    for col in range(n):
        max_row = -1
        max_val = -np.inf
        for row in remaining_rows:
            if abs(A[row, col]) > max_val:
                max_val = abs(A[row, col])
                max_row = row

        if max_row == -1:
            raise ValueError("Матрица не может быть приведена к диагонально-доминирующему виду")
        new_A[col] = A[max_row]
        new_b[col] = b[max_row]
        remaining_rows.remove(max_row)

    for i in range(n):
        row_sum = np.sum(np.abs(new_A[i])) - np.abs(new_A[i, i])
        if np.abs(new_A[i, i]) <= row_sum:
            print("Не удалось достичь строгого диагонального преобладания")

    return new_A, new_b

In [3]:
# Метод простых итераций
def simpiter_method(A, b, max_iter=1000, e=1e-10, ensure_dominance=True):
    if ensure_dominance:
        A, b = make_diagonally_dominant(A, b)

    n = len(b)
    x = np.zeros(n)
    for k in range(max_iter):
        x_new = np.zeros(n)
        for i in range(n):
            s = np.dot(A[i, :], x) - A[i, i] * x[i]
            x_new[i] = (b[i] - s) / A[i, i]
        if np.linalg.norm(x_new - x) < e:
            return x_new, k + 1
        x = x_new.copy()

    print("Достигнуто максимальное число итераций.")
    return x, max_iter

In [4]:
# Метод Зейделя
def seidel_method(A, b, e=1e-10, max_iter=1000, ensure_dominance=True):
    if ensure_dominance:
        A, b = make_diagonally_dominant(A, b)

    n = len(A)
    x = np.zeros(n)
    for iteration in range(max_iter):
        x_prev = np.copy(x)
        for i in range(n):
            sigma = np.dot(A[i, :i], x[:i]) + np.dot(A[i, i + 1:], x[i + 1:])
            x[i] = (b[i] - sigma) / A[i, i]
        if np.linalg.norm(x - x_prev) < e:
            return x, iteration + 1

    print(f"Достигнуто максимальное число итераций ({max_iter})")
    return x, max_iter

In [5]:
# Пример использования
A = np.array([[2, 2, 10],
              [10, 1, 1],
              [2, 10, 1]], dtype=float)
b = np.array([14, 12, 13], dtype=float)

print("Исходная матрица A:")
print(A)
print("Вектор b:", b)

x_si, it_si = simpiter_method(A, b)
print("\nРешение методом простых итераций:")
print("x =", x_si)
print("Итераций:", it_si)
print("Проверка (Ax - b):", np.dot(A, x_si) - b)

x_sz, it_sz = seidel_method(A, b)
print("\nРешение методом Зейделя:")
print("x =", x_sz)
print("Итераций:", it_sz)
print("Проверка (Ax - b):", np.dot(A, x_sz) - b)

Исходная матрица A:
[[ 2.  2. 10.]
 [10.  1.  1.]
 [ 2. 10.  1.]]
Вектор b: [14. 12. 13.]

Решение методом простых итераций:
x = [1. 1. 1.]
Итераций: 21
Проверка (Ax - b): [5.75468562e-11 3.62518904e-11 4.56754634e-11]

Решение методом Зейделя:
x = [1. 1. 1.]
Итераций: 9
Проверка (Ax - b): [ 1.77635684e-15 -2.82440737e-13  1.83852933e-11]
